export { default as AsideComponent } from './aside.component'
export { default as HeaderComponent } from './header.component'
export { default as NavComponent } from './nav.component'
export { default as NoteComponent } from './note.component'
export { default as SectionComponent } from './section.component'
export { default as CreatePostComponent } from './create-post.component'
export { default as ManagerPostComponent } from './manager-post.component'
export { default as ProfileComponent } from './profile.component'
