export { default as User } from "./user";
export { default as Search } from "./search";
export { default as Post } from "./posts";
export { default as Pagination } from "./pagination";
export { default as ModalsPriceAndArea } from "./modals/modalsPriceAndArea";
export { default as ModalsCategoryAndProvince } from "./modals/modalsCategoryAndProvince";
export { default as Loading } from "./loading";
export { default as Input } from "./input";
export { default as UpdatePost } from "./updatePost";

export { default as AuthorAside } from "./author-aside";
export { default as AsideNewPost } from "./aside/aside-new-post";
export { default as AsideNewHot } from "./aside/aside-new-hot";
export { default as AsideArea } from "./aside/aside-area";
export { default as AsideSubLink } from "./aside/aside-subLink";
export { default as AsidePrice } from "./aside/aside-price";
export { default as AsideDirectoryRental } from "./aside/aside-directory-rental";
export { default as AsideNewNews } from "./aside/aside-new-news";
export { default as AsideAcreage } from "./aside/aside-acreage";
